//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FormResources", typeof(FormResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن نفسي.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان العنوان.
        /// </summary>
        public static string AddressTitle {
            get {
                return ResourceManager.GetString("AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاتفاقية.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ص.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص عربي.
        /// </summary>
        public static string ArabicContent {
            get {
                return ResourceManager.GetString("ArabicContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم بالعربية.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف المختصر بالعربية.
        /// </summary>
        public static string ArabicShortDescription {
            get {
                return ResourceManager.GetString("ArabicShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان بالعربية.
        /// </summary>
        public static string ArabicTitle {
            get {
                return ResourceManager.GetString("ArabicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة البانر.
        /// </summary>
        public static string BannerImage {
            get {
                return ResourceManager.GetString("BannerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيرة الذاتية.
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشهادات.
        /// </summary>
        public static string Certifications {
            get {
                return ResourceManager.GetString("Certifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الدولة.
        /// </summary>
        public static string ChooseCountry {
            get {
                return ResourceManager.GetString("ChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المحتوى.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الغلاف.
        /// </summary>
        public static string CoverPhoto {
            get {
                return ResourceManager.GetString("CoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصص.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف بالعربية.
        /// </summary>
        public static string DescriptionAr {
            get {
                return ResourceManager.GetString("DescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف بالإنجليزية.
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلق.
        /// </summary>
        public static string Divorced {
            get {
                return ResourceManager.GetString("Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستند.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليم.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موظف.
        /// </summary>
        public static string Employed {
            get {
                return ResourceManager.GetString("Employed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة العمل.
        /// </summary>
        public static string EmploymentStatus {
            get {
                return ResourceManager.GetString("EmploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص انجليزي.
        /// </summary>
        public static string EnglishContent {
            get {
                return ResourceManager.GetString("EnglishContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالإنجليزية.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف المختصر بالإنجليزية.
        /// </summary>
        public static string EnglishShortDescription {
            get {
                return ResourceManager.GetString("EnglishShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان بالإنجليزية.
        /// </summary>
        public static string EnglishTitle {
            get {
                return ResourceManager.GetString("EnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخبرة.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيس بوك.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل الملفات.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان الكامل.
        /// </summary>
        public static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالكامل.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعرض.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهوايات.
        /// </summary>
        public static string Hobbies {
            get {
                return ResourceManager.GetString("Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايقونة.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انستجرام.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاهتمامات.
        /// </summary>
        public static string Interests {
            get {
                return ResourceManager.GetString("Interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسمى الوظيفي.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكلمات المفتاحية.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغات.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العائلة.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لينكد ان.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة الاجتماعية.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متزوج.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوسائط.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم القومى.
        /// </summary>
        public static string NationalId {
            get {
                return ResourceManager.GetString("NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقرب معلم.
        /// </summary>
        public static string NearestLandmark {
            get {
                return ResourceManager.GetString("NearestLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير ثنائي.
        /// </summary>
        public static string NonBinary {
            get {
                return ResourceManager.GetString("NonBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختياري.
        /// </summary>
        public static string optional {
            get {
                return ResourceManager.GetString("optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to م.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة الخصوصية.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الملف الشخصي.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييم.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متقاعد.
        /// </summary>
        public static string Retired {
            get {
                return ResourceManager.GetString("Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراجعة.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف محرك البحث.
        /// </summary>
        public static string SearchEngineDescription {
            get {
                return ResourceManager.GetString("SearchEngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علامات محرك البحث.
        /// </summary>
        public static string SearchEngineTags {
            get {
                return ResourceManager.GetString("SearchEngineTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان محرك البحث.
        /// </summary>
        public static string SearchEngineTitle {
            get {
                return ResourceManager.GetString("SearchEngineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصطلحات البحث.
        /// </summary>
        public static string SearchTerms {
            get {
                return ResourceManager.GetString("SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف المختصر.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار المقالات.
        /// </summary>
        public static string ShowArticles {
            get {
                return ResourceManager.GetString("ShowArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار الأطباء.
        /// </summary>
        public static string ShowDoctors {
            get {
                return ResourceManager.GetString("ShowDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض فى الصفحة الرئيسية.
        /// </summary>
        public static string ShowInHomePage {
            get {
                return ResourceManager.GetString("ShowInHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار الخدمات.
        /// </summary>
        public static string ShowServices {
            get {
                return ResourceManager.GetString("ShowServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار الأحصائيات.
        /// </summary>
        public static string ShowStatistics {
            get {
                return ResourceManager.GetString("ShowStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اظهار شهادات العملاء.
        /// </summary>
        public static string ShowTestimonials {
            get {
                return ResourceManager.GetString("ShowTestimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعزب.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهارات.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سناب شات.
        /// </summary>
        public static string Snapchat {
            get {
                return ResourceManager.GetString("Snapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص بالعربية.
        /// </summary>
        public static string SpecializationAR {
            get {
                return ResourceManager.GetString("SpecializationAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص بالإنجليزية.
        /// </summary>
        public static string SpecializationEN {
            get {
                return ResourceManager.GetString("SpecializationEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت البداية.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الولاية.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طالب.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال التعليقات.
        /// </summary>
        public static string SubmitFeedback {
            get {
                return ResourceManager.GetString("SubmitFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملخص.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوسوم.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والأحكام.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تيكتوك.
        /// </summary>
        public static string Tiktok {
            get {
                return ResourceManager.GetString("Tiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان بالعربيه.
        /// </summary>
        public static string TitleAr {
            get {
                return ResourceManager.GetString("TitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان بالإنجليزية.
        /// </summary>
        public static string TitleEn {
            get {
                return ResourceManager.GetString("TitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تويتر.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتب.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عاطل عن العمل.
        /// </summary>
        public static string Unemployed {
            get {
                return ResourceManager.GetString("Unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع الإلكتروني.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واتس اب.
        /// </summary>
        public static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرمل.
        /// </summary>
        public static string Widowed {
            get {
                return ResourceManager.GetString("Widowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالتك.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوتيوب.
        /// </summary>
        public static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز البريدي.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
