//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SystemResources", typeof(SystemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا تملك صلاحية الوصول.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف سمة.
        /// </summary>
        public static string AddAttribute {
            get {
                return ResourceManager.GetString("AddAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف إلى عربة التسوق.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم الذكية.
        /// </summary>
        public static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يؤثر على السعر.
        /// </summary>
        public static string AffectsPricing {
            get {
                return ResourceManager.GetString("AffectsPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتداء من .
        /// </summary>
        public static string AsLowAs {
            get {
                return ResourceManager.GetString("AsLowAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخاصية.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصائص.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في Velvora Watches، نؤمن بأن الساعة الرائعة ليست مجرد أداة لقياس الوقت، بل هي تعبير عن الأناقة والرقي..
        /// </summary>
        public static string AtVelvoraWatchesWeBelieveAGreatWatchIsMoreThanJustATimepieceItsAStatementOfStyleAndSophistication {
            get {
                return ResourceManager.GetString("AtVelvoraWatchesWeBelieveAGreatWatchIsMoreThanJustATimepieceItsAStatementOfStyleA" +
                        "ndSophistication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤلف.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأكثر مبيعًا.
        /// </summary>
        public static string BestSellers {
            get {
                return ResourceManager.GetString("BestSellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جلب.
        /// </summary>
        public static string Bring {
            get {
                return ResourceManager.GetString("Bring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بواسطة.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربة التسوق.
        /// </summary>
        public static string cart {
            get {
                return ResourceManager.GetString("cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئات.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصائص الفئة.
        /// </summary>
        public static string CategoryAttributes {
            get {
                return ResourceManager.GetString("CategoryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئه.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانة اختيار.
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شوكولاتة.
        /// </summary>
        public static string Chocolate {
            get {
                return ResourceManager.GetString("Chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عيد الميلاد.
        /// </summary>
        public static string Christmas {
            get {
                return ResourceManager.GetString("Christmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدينه.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللون.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التواصل.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بالدعم.
        /// </summary>
        public static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المحتوى.
        /// </summary>
        public static string ContentManagement {
            get {
                return ResourceManager.GetString("ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلد.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حساب.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم عشري.
        /// </summary>
        public static string DecimalNumber {
            get {
                return ResourceManager.GetString("DecimalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة الخصم.
        /// </summary>
        public static string DiscountPercent {
            get {
                return ResourceManager.GetString("DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتشف الأناقة الخالدة مع ساعاتنا الفاخرة.
        /// </summary>
        public static string DiscoverTimelessEleganceWithOurPremiumWatches {
            get {
                return ResourceManager.GetString("DiscoverTimelessEleganceWithOurPremiumWatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب العرض.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطوّر .NET.
        /// </summary>
        public static string DotNetDeveloper {
            get {
                return ResourceManager.GetString("DotNetDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاية العام.
        /// </summary>
        public static string EndOfTheYear {
            get {
                return ResourceManager.GetString("EndOfTheYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ: 403 - ممنوع الدخول.
        /// </summary>
        public static string ErrorCode403Forbidden {
            get {
                return ResourceManager.GetString("ErrorCode403Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتج حصري.
        /// </summary>
        public static string ExclusiveProducts {
            get {
                return ResourceManager.GetString("ExclusiveProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصم اضافي.
        /// </summary>
        public static string ExtraOff {
            get {
                return ResourceManager.GetString("ExtraOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط فيسبوك.
        /// </summary>
        public static string FacebookLink {
            get {
                return ResourceManager.GetString("FacebookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضة.
        /// </summary>
        public static string Fashion {
            get {
                return ResourceManager.GetString("Fashion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاكس.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتجات مميزة.
        /// </summary>
        public static string FeaturedProducts {
            get {
                return ResourceManager.GetString("FeaturedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحقل.
        /// </summary>
        public static string FieldType {
            get {
                return ResourceManager.GetString("FieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من المدوّنة.
        /// </summary>
        public static string FromTheBlog {
            get {
                return ResourceManager.GetString("FromTheBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احصل على.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق الهدايا.
        /// </summary>
        public static string GiftBox {
            get {
                return ResourceManager.GetString("GiftBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اذهب إلى عيد الميلاد.
        /// </summary>
        public static string GoChristmas {
            get {
                return ResourceManager.GetString("GoChristmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اذهب إلى لوحة التحكم.
        /// </summary>
        public static string GoToAdminPanel {
            get {
                return ResourceManager.GetString("GoToAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الانتقال إلى الصفحة الرئيسية.
        /// </summary>
        public static string GoToHomePage {
            get {
                return ResourceManager.GetString("GoToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطور .NET شغوف بالتعلم، أتمتع بخبرة قوية في تطوير تطبيقات الويب باستخدام MVC و Web API، وأتقن التعامل مع Entity Framework و LINQ..
        /// </summary>
        public static string IAmaPassionateJuniorDotNetDeveloperWithHandsOnExperienceInBuildingWebApplicationsUsingAspNetMvcAndEntityFramework {
            get {
                return ResourceManager.GetString("IAmaPassionateJuniorDotNetDeveloperWithHandsOnExperienceInBuildingWebApplications" +
                        "UsingAspNetMvcAndEntityFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط الانستجرام.
        /// </summary>
        public static string InstagramLink {
            get {
                return ResourceManager.GetString("InstagramLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم صحيح.
        /// </summary>
        public static string IntegerNumber {
            get {
                return ResourceManager.GetString("IntegerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت معالجة الفاتورة بنجاح، وطلبك في الطريق.
        /// </summary>
        public static string InvoiceIsSuccessfullyProcessedAndYourOrderIsOnTheWay {
            get {
                return ResourceManager.GetString("InvoiceIsSuccessfullyProcessedAndYourOrderIsOnTheWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يؤثر على السعر.
        /// </summary>
        public static string IsAffectPrice {
            get {
                return ResourceManager.GetString("IsAffectPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهائي.
        /// </summary>
        public static string IsFinal {
            get {
                return ResourceManager.GetString("IsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمه المنتجات.
        /// </summary>
        public static string ItemList {
            get {
                return ResourceManager.GetString("ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتجات.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البانر الأخير.
        /// </summary>
        public static string LastPanner {
            get {
                return ResourceManager.GetString("LastPanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمه الفئات.
        /// </summary>
        public static string ListOfCategory {
            get {
                return ResourceManager.GetString("ListOfCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمه المنتجات.
        /// </summary>
        public static string ListOfProdct {
            get {
                return ResourceManager.GetString("ListOfProdct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر الاصلي.
        /// </summary>
        public static string ListPrice {
            get {
                return ResourceManager.GetString("ListPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعار.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطول الأقصى.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البانر الأوسط.
        /// </summary>
        public static string MiddlePanner {
            get {
                return ResourceManager.GetString("MiddlePanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة اختيار متعددة.
        /// </summary>
        public static string MultiSelectList {
            get {
                return ResourceManager.GetString("MultiSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابي.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب جديد.
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعة جديدة من الهدايا الرائعة.
        /// </summary>
        public static string NewCollectionOfAwesomeGift {
            get {
                return ResourceManager.GetString("NewCollectionOfAwesomeGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتجات جديدة.
        /// </summary>
        public static string NewProducts {
            get {
                return ResourceManager.GetString("NewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد خصائص متاحة.
        /// </summary>
        public static string NoAttributes {
            get {
                return ResourceManager.GetString("NoAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصم.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمر يسري.
        /// </summary>
        public static string OmarYousry {
            get {
                return ResourceManager.GetString("OmarYousry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتجات مضمونة بجودة 100%.
        /// </summary>
        public static string OneHundredPercentQualityGuaranteedProducts {
            get {
                return ResourceManager.GetString("OneHundredPercentQualityGuaranteedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يعمل فريقنا من المحترفين بلا كلل لضمان رضا العملاء من خلال حلول مبتكرة وجودة في التنفيذ.
        /// </summary>
        public static string OurTeamOfProfessionalsWorksTirelesslyToEnsureCustomerSatisfactionThroughInnovativeSolutionsAndQualityCraftsmanship {
            get {
                return ResourceManager.GetString("OurTeamOfProfessionalsWorksTirelesslyToEnsureCustomerSatisfactionThroughInnovativ" +
                        "eSolutionsAndQualityCraftsmanship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة غير موجودة.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الوالد.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتج.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجودة.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضمان الجودة.
        /// </summary>
        public static string QualityAssurance {
            get {
                return ResourceManager.GetString("QualityAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كميه.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتجات ذات صلة.
        /// </summary>
        public static string RelatedProducts {
            get {
                return ResourceManager.GetString("RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدور.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفيضات.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الدور.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرسل هدية لمن تحب.
        /// </summary>
        public static string SendGiftYourLovedOne {
            get {
                return ResourceManager.GetString("SendGiftYourLovedOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم التسلسلي.
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الإعدادات.
        /// </summary>
        public static string SettingsList {
            get {
                return ResourceManager.GetString("SettingsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاركها.
        /// </summary>
        public static string ShareIt {
            get {
                return ResourceManager.GetString("ShareIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسوّق الآن.
        /// </summary>
        public static string ShopNow {
            get {
                return ResourceManager.GetString("ShopNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف قصير.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض نتائج المنتجات.
        /// </summary>
        public static string ShowingProductsResult {
            get {
                return ResourceManager.GetString("ShowingProductsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بالتسجيل للحصول على حساب مجاني في متجرنا. التسجيل سريع وسهل، ويسمح لك بالطلب من متجرنا. للبدء بالتسوق، اضغط على تسجيل.
        /// </summary>
        public static string SignUpForFreeAccountAtOurStoreRegistrationIsQuickAndEasyItAllowsYouToOrderFromOurShopToStartShoppingClickRegister {
            get {
                return ResourceManager.GetString("SignUpForFreeAccountAtOurStoreRegistrationIsQuickAndEasyItAllowsYouToOrderFromOur" +
                        "ShopToStartShoppingClickRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقاس.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شريط التمرير.
        /// </summary>
        public static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد المبيعات.
        /// </summary>
        public static string SoldCount {
            get {
                return ResourceManager.GetString("SoldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتجات مميزة.
        /// </summary>
        public static string Specialproducts {
            get {
                return ResourceManager.GetString("Specialproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محافظه.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاله المخزون.
        /// </summary>
        public static string StockStatus {
            get {
                return ResourceManager.GetString("StockStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المتجر.
        /// </summary>
        public static string StoreInformation {
            get {
                return ResourceManager.GetString("StoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صور مصغره.
        /// </summary>
        public static string ThumbnailImage {
            get {
                return ResourceManager.GetString("ThumbnailImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفضل الفئات.
        /// </summary>
        public static string TopCategory {
            get {
                return ResourceManager.GetString("TopCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعلى مجموعة.
        /// </summary>
        public static string TopCollection {
            get {
                return ResourceManager.GetString("TopCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجمالي.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر الإجمالي.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط تويتر.
        /// </summary>
        public static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الأنواع.
        /// </summary>
        public static string TypeList {
            get {
                return ResourceManager.GetString("TypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم  النوع.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدات.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصم حتى 50%.
        /// </summary>
        public static string UptoFiftyPercent {
            get {
                return ResourceManager.GetString("UptoFiftyPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيديو.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نطاق الرؤية.
        /// </summary>
        public static string VisibilityScope {
            get {
                return ResourceManager.GetString("VisibilityScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الساعات هي أدوات لقياس الوقت تُرتدى على المعصم أو تُحمل في الجيب. تجمع بين الوظيفة العملية والمظهر الجمالي. إليك وصفًا تفصيليًا للساعات.
        /// </summary>
        public static string WatchesAreTimekeepingDevicesWornOnTheWristOrCarriedInAPocket {
            get {
                return ResourceManager.GetString("WatchesAreTimekeepingDevicesWornOnTheWristOrCarriedInAPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متجر الساعات.
        /// </summary>
        public static string WatchSystem {
            get {
                return ResourceManager.GetString("WatchSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن ملتزمون بتقديم خدمات ومنتجات متميزة لعملائنا.
        /// </summary>
        public static string WeAreDedicatedToProvidingExceptionalServicesAndProductsToOurCustomers {
            get {
                return ResourceManager.GetString("WeAreDedicatedToProvidingExceptionalServicesAndProductsToOurCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبًا بك في متجرنا للساعات.
        /// </summary>
        public static string WelcomeToOurStoreWatch {
            get {
                return ResourceManager.GetString("WelcomeToOurStoreWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية الوصول إلى هذه الصفحة. إذا كنت تعتقد أن هذا حدث عن طريق الخطأ، يرجى التواصل مع المسؤول.
        /// </summary>
        public static string YouDontHavePermissionToAccessThisPagePleaseContactTheAdministratorIfYouBelieveThisIsAnError {
            get {
                return ResourceManager.GetString("YouDontHavePermissionToAccessThisPagePleaseContactTheAdministratorIfYouBelieveThi" +
                        "sIsAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل طلبك.
        /// </summary>
        public static string YourOrderDetails {
            get {
                return ResourceManager.GetString("YourOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط يوتيوب.
        /// </summary>
        public static string YoutubeLink {
            get {
                return ResourceManager.GetString("YoutubeLink", resourceCulture);
            }
        }
    }
}
