//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserResources", typeof(UserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق النشر © 2024 IT Legend.
        /// </summary>
        public static string CopyrightMessage {
            get {
                return ResourceManager.GetString("CopyrightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية مطلوبة..
        /// </summary>
        public static string CurrentPassword_Required {
            get {
                return ResourceManager.GetString("CurrentPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني &apos;{0}&apos; مستخدم بالفعل..
        /// </summary>
        public static string Email_Duplicate {
            get {
                return ResourceManager.GetString("Email_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني مطلوب..
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كان من المتوقع أن يكون المستخدم مثيلًا..
        /// </summary>
        public static string Expected_UserInstance {
            get {
                return ResourceManager.GetString("Expected_UserInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إرسال رمز التفعيل..
        /// </summary>
        public static string FailedToSendVerificationCode {
            get {
                return ResourceManager.GetString("FailedToSendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعيد برؤيتك مرة أخرى!.
        /// </summary>
        public static string HappyToSeeYouMessage {
            get {
                return ResourceManager.GetString("HappyToSeeYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صالح..
        /// </summary>
        public static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم أو كلمة المرور غير صحيحة..
        /// </summary>
        public static string Invalid_UsernamePassword_Couple {
            get {
                return ResourceManager.GetString("Invalid_UsernamePassword_Couple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التفعيل غير صالح أو منتهي الصلاحية..
        /// </summary>
        public static string InvalidOrExpiredCode {
            get {
                return ResourceManager.GetString("InvalidOrExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أبقني مسجل الدخول.
        /// </summary>
        public static string KeepMeSignedIn {
            get {
                return ResourceManager.GetString("KeepMeSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بتسجيل الدخول إلى حسابك للوصول إلى الميزات وإدارة لوحة التحكم بسهولة..
        /// </summary>
        public static string LoginPageDescription {
            get {
                return ResourceManager.GetString("LoginPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحباً بك في.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسوق.
        /// </summary>
        public static string Marketer {
            get {
                return ResourceManager.GetString("Marketer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة مطلوبة..
        /// </summary>
        public static string NewPassword_Required {
            get {
                return ResourceManager.GetString("NewPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير صحيحة..
        /// </summary>
        public static string Password_Mismatch {
            get {
                return ResourceManager.GetString("Password_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور مطلوبة..
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تحتوي كلمات المرور على حرف رقمي واحد على الأقل (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string Password_RequiresDigit {
            get {
                return ResourceManager.GetString("Password_RequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تحتوي كلمات المرور على حرف صغير واحد على الأقل (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string Password_RequiresLower {
            get {
                return ResourceManager.GetString("Password_RequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تحتوي كلمات المرور على حرف غير حرف أو رقم واحد على الأقل..
        /// </summary>
        public static string Password_RequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("Password_RequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تحتوي كلمات المرور على حرف كبير واحد على الأقل (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string Password_RequiresUpper {
            get {
                return ResourceManager.GetString("Password_RequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم السري قصير جداَ..
        /// </summary>
        public static string Password_Too_Short {
            get {
                return ResourceManager.GetString("Password_Too_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة وتأكيد كلمة المرور غير متطابقين..
        /// </summary>
        public static string PasswordConfirmation_Mismatch {
            get {
                return ResourceManager.GetString("PasswordConfirmation_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف &apos;{0}&apos; مستخدم بالفعل..
        /// </summary>
        public static string PhoneNumber_Duplicate {
            get {
                return ResourceManager.GetString("PhoneNumber_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز إعادة التعيين غير صالح. يرجى طلب رمز جديد..
        /// </summary>
        public static string ResetToken_Invalid {
            get {
                return ResourceManager.GetString("ResetToken_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشرف.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوكين مطلوب..
        /// </summary>
        public static string Token_Required {
            get {
                return ResourceManager.GetString("Token_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ غير متوقع: &apos;{0}&apos;..
        /// </summary>
        public static string Unexpected_Error {
            get {
                return ResourceManager.GetString("Unexpected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تأكيد عنوان بريدك الإلكتروني. يرجى تأكيد بريدك الإلكتروني قبل أن تتمكن من تسجيل الدخول..
        /// </summary>
        public static string User_EmailNotConfirmed {
            get {
                return ResourceManager.GetString("User_EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم مغلق..
        /// </summary>
        public static string User_LockedOut {
            get {
                return ResourceManager.GetString("User_LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم المحدد غير مسموح له بتسجيل الدخول..
        /// </summary>
        public static string User_NotAllowed {
            get {
                return ResourceManager.GetString("User_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم المحدد غير مسموح له بتسجيل الدخول باستخدام المصادقة بكلمة المرور..
        /// </summary>
        public static string User_RequiresTwoFactor {
            get {
                return ResourceManager.GetString("User_RequiresTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل المستخدم بنجاح..
        /// </summary>
        public static string UserActivatedSuccessfully {
            get {
                return ResourceManager.GetString("UserActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في تفعيل المستخدم..
        /// </summary>
        public static string UserActivationFailed {
            get {
                return ResourceManager.GetString("UserActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم &apos;{0}&apos; مستخدم بالفعل..
        /// </summary>
        public static string UserName_Duplicate {
            get {
                return ResourceManager.GetString("UserName_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم &apos;{0}&apos; غير صالح، يمكن أن يحتوي فقط على الأحرف أو الأرقام..
        /// </summary>
        public static string UserName_Invalid {
            get {
                return ResourceManager.GetString("UserName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم مطلوب..
        /// </summary>
        public static string Username_Required {
            get {
                return ResourceManager.GetString("Username_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على المستخدم..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إرسال رمز التحقق. يرجى المحاولة مرة أخرى..
        /// </summary>
        public static string VerificationCodeError {
            get {
                return ResourceManager.GetString("VerificationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رمز التفعيل الجديد إلى جوالك..
        /// </summary>
        public static string VerificationCodeSent {
            get {
                return ResourceManager.GetString("VerificationCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا بعودتك!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
