//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان يجب أن يكون بين 2 و 100 حرف..
        /// </summary>
        public static string AddressLength {
            get {
                return ResourceManager.GetString("AddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان مطلوب..
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرّف الميزة مطلوب..
        /// </summary>
        public static string AmenityIdRequired {
            get {
                return ResourceManager.GetString("AmenityIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة مطلوبة..
        /// </summary>
        public static string AreaIdRequired {
            get {
                return ResourceManager.GetString("AreaIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون عدد الحمامات عددًا صحيحًا إيجابيًا..
        /// </summary>
        public static string BathroomsRange {
            get {
                return ResourceManager.GetString("BathroomsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحمامات مطلوب..
        /// </summary>
        public static string BathroomsRequired {
            get {
                return ResourceManager.GetString("BathroomsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون عدد غرف النوم عددًا صحيحًا إيجابيًا..
        /// </summary>
        public static string BedroomsRange {
            get {
                return ResourceManager.GetString("BedroomsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد غرف النوم مطلوب..
        /// </summary>
        public static string BedroomsRequired {
            get {
                return ResourceManager.GetString("BedroomsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون مساحة البناء عددًا إيجابيًا..
        /// </summary>
        public static string BuiltUpAreaRange {
            get {
                return ResourceManager.GetString("BuiltUpAreaRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحة البناء مطلوبة..
        /// </summary>
        public static string BuiltUpAreaRequired {
            get {
                return ResourceManager.GetString("BuiltUpAreaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكل السيارة مطلوب..
        /// </summary>
        public static string CarShapeRequired {
            get {
                return ResourceManager.GetString("CarShapeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة مطلوبة..
        /// </summary>
        public static string CityIdRequired {
            get {
                return ResourceManager.GetString("CityIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجمع مطلوب..
        /// </summary>
        public static string CompoundIdRequired {
            get {
                return ResourceManager.GetString("CompoundIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون هناك صورة مجمع واحدة على الأقل..
        /// </summary>
        public static string CompoundImagesRequired {
            get {
                return ResourceManager.GetString("CompoundImagesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد ؟.
        /// </summary>
        public static string ConfirmPrompt {
            get {
                return ResourceManager.GetString("ConfirmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى العربي يجب أن يكون بين 10 و 5000 حرف..
        /// </summary>
        public static string ContentArLength {
            get {
                return ResourceManager.GetString("ContentArLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى العربي مطلوب..
        /// </summary>
        public static string ContentArRequired {
            get {
                return ResourceManager.GetString("ContentArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى الإنجليزي يجب أن يكون بين 10 و 5000 حرف..
        /// </summary>
        public static string ContentEnLength {
            get {
                return ResourceManager.GetString("ContentEnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى الإنجليزي مطلوب..
        /// </summary>
        public static string ContentEnRequired {
            get {
                return ResourceManager.GetString("ContentEnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اضافة محتوى..
        /// </summary>
        public static string ContentMustBeAdded {
            get {
                return ResourceManager.GetString("ContentMustBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى مطلوب..
        /// </summary>
        public static string ContentRequired {
            get {
                return ResourceManager.GetString("ContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز البلد يجب أن يكون بين 1 و 5 أحرف..
        /// </summary>
        public static string CountryCodeLength {
            get {
                return ResourceManager.GetString("CountryCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز البلد مطلوب..
        /// </summary>
        public static string CountryCodeRequired {
            get {
                return ResourceManager.GetString("CountryCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة مطلوبة..
        /// </summary>
        public static string CountryIdRequired {
            get {
                return ResourceManager.GetString("CountryIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح..
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بمجرد الحذف ، لن تتمكن من استرداده !!.
        /// </summary>
        public static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنة التسليم يجب أن تكون بين 1900 و 2100..
        /// </summary>
        public static string DeliveryYearRange {
            get {
                return ResourceManager.GetString("DeliveryYearRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنة التسليم مطلوبة..
        /// </summary>
        public static string DeliveryYearRequired {
            get {
                return ResourceManager.GetString("DeliveryYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف العربي يجب أن يكون بين 10 و 1000 حرف..
        /// </summary>
        public static string DescriptionArLength {
            get {
                return ResourceManager.GetString("DescriptionArLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف العربي مطلوب..
        /// </summary>
        public static string DescriptionArRequired {
            get {
                return ResourceManager.GetString("DescriptionArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف الإنجليزي يجب أن يكون بين 10 و 1000 حرف..
        /// </summary>
        public static string DescriptionEnLength {
            get {
                return ResourceManager.GetString("DescriptionEnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف الإنجليزي مطلوب..
        /// </summary>
        public static string DescriptionEnRequired {
            get {
                return ResourceManager.GetString("DescriptionEnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المطور مطلوب..
        /// </summary>
        public static string DeveloperIdRequired {
            get {
                return ResourceManager.GetString("DeveloperIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل يجب أن يكون بين 1% و 100%.
        /// </summary>
        public static string DiscountPercentLength {
            get {
                return ResourceManager.GetString("DiscountPercentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون نسبة الدفع المقدم بين 0 و 100..
        /// </summary>
        public static string DownPaymentPercentageRange {
            get {
                return ResourceManager.GetString("DownPaymentPercentageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة الدفع المقدم مطلوبة..
        /// </summary>
        public static string DownPaymentPercentageRequired {
            get {
                return ResourceManager.GetString("DownPaymentPercentageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني ليس بتنسيق صحيح..
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان البريد الإلكتروني غير صحيح..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني مطلوب..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانتهاء مطلوب..
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور عليه ..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط فيسبوك غير صحيح..
        /// </summary>
        public static string FacebookInvalid {
            get {
                return ResourceManager.GetString("FacebookInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل يجب أن يكون بين 2 و 100 حرف.
        /// </summary>
        public static string FieldLength {
            get {
                return ResourceManager.GetString("FieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب ..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون حالة التشطيب عددًا صحيحًا إيجابيًا..
        /// </summary>
        public static string FinishingStatusRange {
            get {
                return ResourceManager.GetString("FinishingStatusRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة التشطيب مطلوبة..
        /// </summary>
        public static string FinishingStatusRequired {
            get {
                return ResourceManager.GetString("FinishingStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط صورة المخطط الطابقي لا يمكن أن يتجاوز 500 حرف..
        /// </summary>
        public static string FloorPlanImageLength {
            get {
                return ResourceManager.GetString("FloorPlanImageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة المخطط الطابقي مطلوبة..
        /// </summary>
        public static string FloorPlanImageRequired {
            get {
                return ResourceManager.GetString("FloorPlanImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل يجب أن يكون بين 2 و 100 حرف..
        /// </summary>
        public static string FullNameLength {
            get {
                return ResourceManager.GetString("FullNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل مطلوب..
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع مطوب..
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأيقونة يجب أن تكون بين 2 و 50 حرف..
        /// </summary>
        public static string IconLength {
            get {
                return ResourceManager.GetString("IconLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأيقونة مطلوبة..
        /// </summary>
        public static string IconRequired {
            get {
                return ResourceManager.GetString("IconRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط الصورة لا يمكن أن يتجاوز 500 حرف..
        /// </summary>
        public static string ImageLength {
            get {
                return ResourceManager.GetString("ImageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة مطلوبة..
        /// </summary>
        public static string ImageRequired {
            get {
                return ResourceManager.GetString("ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط إنستغرام غير صحيح..
        /// </summary>
        public static string InstagramInvalid {
            get {
                return ResourceManager.GetString("InstagramInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني أو كلمة المرور غير صحيحة.
        /// </summary>
        public static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنسيق الحقل غير صحيح..
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط غير صحيح..
        /// </summary>
        public static string InvalidLink {
            get {
                return ResourceManager.GetString("InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم القومى المقدم غير صالح للبلد المحدد..
        /// </summary>
        public static string InvalidNationalId {
            get {
                return ResourceManager.GetString("InvalidNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف المقدم غير صالح للبلد المحدد..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشكلة يجب أن يكون بين 2 و 100 حرف..
        /// </summary>
        public static string IssueLength {
            get {
                return ResourceManager.GetString("IssueLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشكلة مطلوبة..
        /// </summary>
        public static string IssueRequired {
            get {
                return ResourceManager.GetString("IssueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون مساحة الأرض عددًا إيجابيًا..
        /// </summary>
        public static string LandAreaRange {
            get {
                return ResourceManager.GetString("LandAreaRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحة الأرض مطلوبة..
        /// </summary>
        public static string LandAreaRequired {
            get {
                return ResourceManager.GetString("LandAreaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط العرض يجب أن يكون بين -90 و 90..
        /// </summary>
        public static string LatitudeRange {
            get {
                return ResourceManager.GetString("LatitudeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط العرض مطلوب..
        /// </summary>
        public static string LatitudeRequired {
            get {
                return ResourceManager.GetString("LatitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون الطول عددًا صحيحًا إيجابيًا..
        /// </summary>
        public static string LengthRange {
            get {
                return ResourceManager.GetString("LengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطول مطلوب..
        /// </summary>
        public static string LengthRequired {
            get {
                return ResourceManager.GetString("LengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط لينكدإن غير صحيح..
        /// </summary>
        public static string LinkedInInvalid {
            get {
                return ResourceManager.GetString("LinkedInInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  . فشل أثناء تحميل البيانات.
        /// </summary>
        public static string LoadDataFailed {
            get {
                return ResourceManager.GetString("LoadDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط الشعار لا يمكن أن يتجاوز 500 حرف..
        /// </summary>
        public static string LogoLength {
            get {
                return ResourceManager.GetString("LogoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشعار مطلوب..
        /// </summary>
        public static string LogoRequired {
            get {
                return ResourceManager.GetString("LogoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط الطول يجب أن يكون بين -180 و 180..
        /// </summary>
        public static string LongitudeRange {
            get {
                return ResourceManager.GetString("LongitudeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط الطول مطلوب..
        /// </summary>
        public static string LongitudeRequired {
            get {
                return ResourceManager.GetString("LongitudeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط صورة المخطط الرئيسي لا يمكن أن يتجاوز 500 حرف..
        /// </summary>
        public static string MasterPlanImageLength {
            get {
                return ResourceManager.GetString("MasterPlanImageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة المخطط الرئيسي مطلوبة..
        /// </summary>
        public static string MasterPlanImageRequired {
            get {
                return ResourceManager.GetString("MasterPlanImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن يتجاوز الحقل {0} حرف..
        /// </summary>
        public static string MaxLengthExceeded {
            get {
                return ResourceManager.GetString("MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة لا يمكن أن تتجاوز 1000 حرف..
        /// </summary>
        public static string MessageMaxLength {
            get {
                return ResourceManager.GetString("MessageMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة مطلوبة..
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف المحمول ليس بتنسيق صحيح..
        /// </summary>
        public static string MobileFormat {
            get {
                return ResourceManager.GetString("MobileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف المحمول يجب أن يكون بين 10 و 15 حرف..
        /// </summary>
        public static string MobileLength {
            get {
                return ResourceManager.GetString("MobileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف مطلوب..
        /// </summary>
        public static string MobileRequired {
            get {
                return ResourceManager.GetString("MobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم (عربي) يجب أن يكون بين 2 و 100 حرف..
        /// </summary>
        public static string NameArLength {
            get {
                return ResourceManager.GetString("NameArLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالعربية مطلوب..
        /// </summary>
        public static string NameArRequired {
            get {
                return ResourceManager.GetString("NameArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم (إنجليزي) يجب أن يكون بين 2 و 100 حرف..
        /// </summary>
        public static string NameEnLength {
            get {
                return ResourceManager.GetString("NameEnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالإنجليزية مطلوب..
        /// </summary>
        public static string NameEnRequired {
            get {
                return ResourceManager.GetString("NameEnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد تغييرات لحفظها..
        /// </summary>
        public static string NoChangesToSave {
            get {
                return ResourceManager.GetString("NoChangesToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون طول هذا الحقل على الأكثر {1} حرفًا ..
        /// </summary>
        public static string OutOfMaxLength {
            get {
                return ResourceManager.GetString("OutOfMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباقة مطلوبة..
        /// </summary>
        public static string PackageRequired {
            get {
                return ResourceManager.GetString("PackageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسار لا يمكن أن يتجاوز 500 حرف..
        /// </summary>
        public static string PathMaxLength {
            get {
                return ResourceManager.GetString("PathMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسار مطلوب..
        /// </summary>
        public static string PathRequired {
            get {
                return ResourceManager.GetString("PathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطة الدفع مطلوبة..
        /// </summary>
        public static string PaymentPlanIdRequired {
            get {
                return ResourceManager.GetString("PaymentPlanIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرحلة مطلوبة..
        /// </summary>
        public static string PhaseIdRequired {
            get {
                return ResourceManager.GetString("PhaseIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف يجب أن يكون بين 10 و 15 حرف..
        /// </summary>
        public static string PhoneLength {
            get {
                return ResourceManager.GetString("PhoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف مطلوب..
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل يجب ان يكون بين 1 و 100000000.
        /// </summary>
        public static string PriceLength {
            get {
                return ResourceManager.GetString("PriceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اضافة السعر..
        /// </summary>
        public static string PriceMustBeAdded {
            get {
                return ResourceManager.GetString("PriceMustBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون السعر عددًا إيجابيًا..
        /// </summary>
        public static string PriceRange {
            get {
                return ResourceManager.GetString("PriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر مطلوب..
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة مطلوبة..
        /// </summary>
        public static string PropertyIdRequired {
            get {
                return ResourceManager.GetString("PropertyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الوحدة مطلوب..
        /// </summary>
        public static string PropertyTypeIdRequired {
            get {
                return ResourceManager.GetString("PropertyTypeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل يجب ان يكون بين 1 و 10 .
        /// </summary>
        public static string RangeDisplayOrder {
            get {
                return ResourceManager.GetString("RangeDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون نسبة الدفع بالاستلام بين 0 و 100..
        /// </summary>
        public static string ReceiptPaymentPercentageRange {
            get {
                return ResourceManager.GetString("ReceiptPaymentPercentageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى التحقق من أنك لست روبوتًا..
        /// </summary>
        public static string RobotValidate {
            get {
                return ResourceManager.GetString("RobotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون سعر البيع عددًا إيجابيًا..
        /// </summary>
        public static string SalesPriceRange {
            get {
                return ResourceManager.GetString("SalesPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر البيع مطلوب..
        /// </summary>
        public static string SalesPriceRequired {
            get {
                return ResourceManager.GetString("SalesPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون نوع البيع عددًا صحيحًا إيجابيًا..
        /// </summary>
        public static string SaleTypeRange {
            get {
                return ResourceManager.GetString("SaleTypeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع البيع مطلوب..
        /// </summary>
        public static string SaleTypeRequired {
            get {
                return ResourceManager.GetString("SaleTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح..
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الخدمات مطلوب..
        /// </summary>
        public static string ServiceCountRequired {
            get {
                return ResourceManager.GetString("ServiceCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الخدمة مطلوب..
        /// </summary>
        public static string ServiceIdRequired {
            get {
                return ResourceManager.GetString("ServiceIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمة مطلوبة..
        /// </summary>
        public static string ServiceRequired {
            get {
                return ResourceManager.GetString("ServiceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف القصير العربي يجب أن يكون بين 10 و 1000 حرف..
        /// </summary>
        public static string ShortDescriptionArLength {
            get {
                return ResourceManager.GetString("ShortDescriptionArLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف القصير العربي مطلوب..
        /// </summary>
        public static string ShortDescriptionArRequired {
            get {
                return ResourceManager.GetString("ShortDescriptionArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف القصير الإنجليزي يجب أن يكون بين 10 و 1000 حرف..
        /// </summary>
        public static string ShortDescriptionEnLength {
            get {
                return ResourceManager.GetString("ShortDescriptionEnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف القصير الإنجليزي مطلوب..
        /// </summary>
        public static string ShortDescriptionEnRequired {
            get {
                return ResourceManager.GetString("ShortDescriptionEnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص بالعربية مطلوب..
        /// </summary>
        public static string SpecializationARRequired {
            get {
                return ResourceManager.GetString("SpecializationARRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص بالإنجليزية مطلوب..
        /// </summary>
        public static string SpecializationENRequired {
            get {
                return ResourceManager.GetString("SpecializationENRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البدء مطلوب..
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار وقت البداية..
        /// </summary>
        public static string StartTimeMustBeSelected {
            get {
                return ResourceManager.GetString("StartTimeMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان العربي يجب أن يكون بين 2 و 100حرف..
        /// </summary>
        public static string TitleArLength {
            get {
                return ResourceManager.GetString("TitleArLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان العربي مطلوب..
        /// </summary>
        public static string TitleArRequired {
            get {
                return ResourceManager.GetString("TitleArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان الإنجليزي يجب أن يكون بين 2 و 100 حرف..
        /// </summary>
        public static string TitleEnLength {
            get {
                return ResourceManager.GetString("TitleEnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان الإنجليزي مطلوب..
        /// </summary>
        public static string TitleEnRequired {
            get {
                return ResourceManager.GetString("TitleEnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط تويتر غير صحيح..
        /// </summary>
        public static string TwitterInvalid {
            get {
                return ResourceManager.GetString("TwitterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون النوع عددًا صحيحًا موجبًا..
        /// </summary>
        public static string TypeRange {
            get {
                return ResourceManager.GetString("TypeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع مطلوب..
        /// </summary>
        public static string TypeRequired {
            get {
                return ResourceManager.GetString("TypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير متوقع :.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم مطلوب..
        /// </summary>
        public static string UserRequired {
            get {
                return ResourceManager.GetString("UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن تكون القيمة فارغة ..
        /// </summary>
        public static string ValueCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الواتساب غير صحيح..
        /// </summary>
        public static string WhatsAppInvalid {
            get {
                return ResourceManager.GetString("WhatsAppInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الواتساب مطلوب..
        /// </summary>
        public static string WhatsAppRequired {
            get {
                return ResourceManager.GetString("WhatsAppRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون العرض عددًا صحيحًا إيجابيًا..
        /// </summary>
        public static string WidthRange {
            get {
                return ResourceManager.GetString("WidthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العرض مطلوب..
        /// </summary>
        public static string WidthRequired {
            get {
                return ResourceManager.GetString("WidthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون سنوات الاستلام بين 1 و 100..
        /// </summary>
        public static string YearsToReceiveRange {
            get {
                return ResourceManager.GetString("YearsToReceiveRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنوات الاستلام مطلوبة..
        /// </summary>
        public static string YearsToReceiveRequired {
            get {
                return ResourceManager.GetString("YearsToReceiveRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط يوتيوب غير صحيح..
        /// </summary>
        public static string YouTubeInvalid {
            get {
                return ResourceManager.GetString("YouTubeInvalid", resourceCulture);
            }
        }
    }
}
